In [1]:
import numpy as np
np.__version__

'1.24.3'

## 차원 반환 (.ndim)

In [30]:
#0차원, Scalar, 점
a0 = np.array(0)
a0, a0.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [31]:
#1차원, Vector, 선
a1 = np.array([2, 4, 6])
a1, a1.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [32]:
#2차원, Matrix, 면
a2 = np.array( [[1,2,3], [4,5,6]] )
a2, a2.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [33]:
#3차원, Tensor, 공간
a3 = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a3, a3.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

## 구조 반환(.shape)

In [37]:
a0.shape # 행렬아님

()

In [38]:
a1.shape

(3,)

In [39]:
a2.shape

(2, 3)

In [40]:
a3.shape

(2, 2, 3)

## 요소의 수 반환(.size)

In [41]:
a2.size

6

In [42]:
a3.size

12

## 배열 생성(np.array())

In [43]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [44]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [45]:
myArr

array([10, 56, 77, 23, 44])

In [48]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30]], 2)

In [49]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[ 1  2  3]
 [10 20 30]] <class 'numpy.ndarray'> 2
차원= 2, 구조 = (2, 3) 구조타입 = <class 'tuple'>, size = 6


In [50]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [51]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
- 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)  
- 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등  
- 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능  

### 리스트 연산

In [52]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [53]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

### 넘파이 연산

In [54]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [55]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


# NumPy 기초

In [8]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print('a.shape:', a.shape)             # 어레이의 차원
print('a.ndim:', a.ndim)               # 어레이의 축의 개수
print('a.dtype.name:', a.dtype.name)   # 어레이 요소의 타입
print('a.itemsize:', a.itemsize)       # 어레이 요소의 바이트 크기
print('a.size:', a.size)               # 어레이 요소의 총 개수
print('type(a):', type(a))             # 어레이의 타입

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape: (3, 5)
a.ndim: 2
a.dtype.name: int32
a.itemsize: 4
a.size: 15
type(a): <class 'numpy.ndarray'>


# array 생성

In [9]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b)
print(type(b))
print(b.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
[1.2 3.5 5.1]
<class 'numpy.ndarray'>
float64


In [10]:
a = np.array(1,2,3,4)    # WRONG -> 생성 불가
b = np.array([1,2,3,4])  # RIGHT -> 리스트 형태
c = np.array((1,2,3,4))  # RIGHT -> 튜플 형태

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [11]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
a = np.array([[1,2], [3,4]], dtype=complex) #타입 지정
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [13]:
'''
np.zeros(), np.ones(), np.empty() 
 -> 어레이의 크기는 알지만 요소의 값이 정해지지 않았을 경우, 어레이 초기화
'''
a = np.zeros(10) #모두 0으로 채워진 어레이 생성
print(a)

b = np.ones((2,3,4), dtype=np.int16) #모두 1로 채워진 어레이 생성 
print(b)

c = np.empty((2,3)) # 요소의 초기값 임의로 지정, 메모리의 상태에 따라 결정됨
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.22522461e-306 6.23058028e-307 2.22526399e-307]]


In [14]:
'''
np.arange() -> 연속적인 숫자들을 만들어 내기 위해 사용
'''
a = np.arange(10, 30, 5) #10~30 사이의 범위에서 step=5를 갖는 어레이 생성
b = np.arange(0, 2, 0.3) #0~2 사이의 범위에서 step=0.3을 갖는 어레이 생성

print(a)
print(b)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [20]:
from numpy import pi

a = np.linspace(0, 2, 9)
print(a)

x = np.linspace(0, 2*pi, 100)
print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

# array 출력

In [21]:
a = np.arange(6)                         # 1d array
print(a)

b = np.arange(12).reshape(4,3)           # 2d array
print(b)

c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [23]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# 기본연산

In [24]:
a = np.array([20,30,40,50])
b = np.arange(4)

c = a - b
print(c)

[20 29 38 47]


In [25]:
print(b**2)
print(10*np.sin(a))
print(a<35)

[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [26]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

print(A * B)                    # elementwise product
print(A @ B)                    # matrix product
print(A.dot(B))                 # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
